"""empty message

Revision ID: 67fffc62dfc6
Revises: e4c369dfb056
Create Date: 2019-09-18 15:33:30.457287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fffc62dfc6'
down_revision = 'e4c369dfb056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
