"""empty message

Revision ID: a00b26a18aed
Revises: 9c32152b0e72
Create Date: 2019-09-17 17:31:58.829367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00b26a18aed'
down_revision = '9c32152b0e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_person')
    op.drop_table('article')
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='article_pkey')
    )
    op.create_table('standard_person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('perne', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('begda', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('endda', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('massn', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('zczlx', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('massg', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('zczyy', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('stat1', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('zkhtd', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('stat2', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('zgyzt', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('aedat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('zflag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('insert_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='standard_person_pkey')
    )
    # ### end Alembic commands ###
